version: "3.8"
services:
    bb-master:
        container_name: bb-master-container
        hostname: bb-master
        user: bb-master:root
        build:
            context: ./bb-master
            dockerfile: Containerfile
        ports:
            # Port to Try-Scheduler
            - "8031:8031"
            # Web Frontend
            - "8010:8010"
        # Only workers must reach the workers-port,
        # hence we only expose but not publish it on the host.
        expose:
            # Workers Port
            - "9989"
        volumes:
            - "./bb-master/cfg:/home/bb-master/cfg:Z"
        environment:
            BUILDBOT_MASTER_TITLE: "Compose"
            BUILDBOT_MASTER_TRY_PORT: "8031"
            BUILDBOT_MASTER_PORT: "9989"
            BUILDBOT_WWW_PORT: "8010"
            # See bb-reverse-proxy container below 
            BUILDBOT_WWW_URL: https://localhost:8443/
        networks:
            - bb-master
            - bb-worker
        healthcheck:
            test: ["CMD", "curl", "-f", "--insecure", "https://localhost:8010"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s

    # This acts as the SSL reverse proxy to buildbot
    bb-reverse-proxy:
        container_name: bb-reverse-proxy-container
        hostname: bb-reverse-proxy
        build:
            context: ./bb-reverse-proxy
            dockerfile: Containerfile
        volumes:
            - "./bb-reverse-proxy/conf/nginx.conf:/etc/nginx/nginx.conf:Z"
        ports:
            - "8443:8443"
            # - "8080:8080"
        depends_on:
            - bb-master
        networks:
            - bb-master
            - bb-worker

    # Spawn 3 buildbot workers one after another and share the basic settings.

    bb-worker1: &worker
        container_name: bb-worker-container-1
        hostname: bb-worker-1
        build:
            context: ./bb-worker
            dockerfile: Containerfile
        environment: &worker-environment
            BUILDBOT_WORKER_NAME: worker1
            BUILDBOT_INFO_ADMIN: you@me.com
            BUILDBOT_MASTER: bb-master:9989
            BUILDBOT_WORKER_PASSWORD: "W0rk3rP@55w0rd"
        networks:
            - bb-worker
        depends_on:
            - bb-master
    
    # We use YAML Fragments to only override where workers are different
    bb-worker2:
        <<: *worker
        hostname: bb-worker-2
        container_name: bb-worker-container-2
        environment:
            <<: *worker-environment
            BUILDBOT_WORKER_NAME: worker2
        depends_on:
            - bb-worker1

    bb-worker3:
        <<: *worker
        hostname: bb-worker-3
        container_name: bb-worker-container-3
        environment:
            <<: *worker-environment
            BUILDBOT_WORKER_NAME: worker3
        depends_on:
            - bb-worker2

networks:
    bb-master: {}
    bb-worker: {}